### PR TITLE
Shoaib019

### PR DESCRIPTION
**Pull request by Shoaib19**
solved problem 169 Majority Element

### CODE REVIEW

**Comment by saadfareed** [comment]
@Shoaib19 place leetcode.cpp in cpp folder.

**Comment by saadfareed** [comment]
@Shoaib19 Also write the proper name of the file instead of leetcode.cpp

**Comment by Shoaib19** [comment]
that is not my file let me fix the pr
thanks

**Comment by Shoaib19** [comment]
@saadfareed can you help me [9371d4c] only this last commit is mine others are not 
how I get this file to my branch

**Comment by saadfareed** [comment]
@Shoaib19 Just place this file in the respective folder and then do these steps.. 

 git add .
git commit - m "Feedback resolve"
git push with your branch name

**Comment by Shoaib19** [comment]
@saadfareed is problem resolved because i didn't done anything I just read your comment now.

**Pull request merged**
