### PR TITLE
added missing brackets

### PR DESCRIPTION
**Pull request by Shoaib19**

### CODE REVIEW

**Comment by Shoaib19** [comment]
apart from this PR there is one pr in queue which requires your attention.
Second thing is I have some code which is practice code but not from leet code if you allow I can create seperate PR for that 
question with my solutions into them.

**Comment by saadfareed** [comment]
Oke you can go for it

**Comment by Shoaib19** [comment]
thanks
 I will do it this weekend

**Comment by saadfareed** [comment]
sure

**Pull request merged**
